# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs


# Simulation parameters
sim_params:
    sim_name: 'AbacusSummit_base_c000_ph000'                                 # which simulation
    sim_dir: /global/cfs/cdirs/desi/public/cosmosim/AbacusSummit/              # where is the simulation
    output_dir: '/pscratch/sd/s/siyizhao/fihobi/mocks_bestfit_y3xi0/'          # where to output galaxy mocks
    subsample_dir: '/pscratch/sd/s/siyizhao/fihobi/subsample/'                 # where to output subsample data
    z_mock: 0.8                                                              # which redshift slice
    cleaned_halos: True                                                     # load cleaned halos?

prepare_sim:
    Nparallel_load: 5                                          # number of processes. peak memory usage will increase by this factor.
    Nthread_per_load: 'auto'                                   # number of threads per process (auto uses the affinity mask)

# HOD parameters
HOD_params:
    want_ranks: False               # want to implement satellite profile flexiblities?
    want_AB: False                  # are you planning on implementing assembly bias (AB)?
    # Ndim: 1024                     # size of grid for grid based local environment, we opted to use neighbor count based local environment instead
    density_sigma: 3               # scale radius in Mpc / h for local density calculation
    tracer_flags:                  # which tracer do we want?
        LRG: True
        ELG: False
        QSO: False
    want_rsd: True                 # want RSD?
    write_to_disk: True

    # parameters for setting up the HOD of LRGs
    LRG_params:
        logM_cut: 13.67
        logM1: 14.048
        sigma: 0.659
        alpha: 0.862
        kappa: 0.0328
        alpha_c: 0
        alpha_s: 1
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0
        ic: 1.0

# clustering parameters
clustering_params:
    power_type: 'wp'
    # clustering_type: 'xirppi'
    bin_params:
        logmin: -1.0437916549520927
        logmax: 1.4771212547196624
        nbins: 29
    pimax: 40
    pi_bin_size: 80
    clustering_type: 'multipole'  # multipole clustering
    sbin_params:
        logmin: -0.9568636
        logmax: 1.47712
        nbins: 28
    mu_bin_size: 200  # number of mu bins for multipole clustering
