path_chain: '../data/l/HOD_fit_y3/dynesty/nest_results.npz'
path_info: 'output/y3.txt'
path_plot_run : 'plot/y3_run.png'
path_plot_trace : 'plot/y3_trace.png'
path_plot_corner : 'plot/y3_corner.png'
path_plot_getdist : 'plot/y3_getdist.png'
path_hod : 'plot/hod_stat_y3.png'