# Comment out the probes you don't need
# CAREFUL: yaml is super sensitive to spaces - don't use tabs


# Simulation parameters
sim_params:
    sim_name: 'AbacusSummit_base_c000_ph000'                                 # which simulation
    sim_dir: /global/cfs/cdirs/desi/public/cosmosim/AbacusSummit/              # where is the simulation
    output_dir: '/pscratch/sd/s/siyizhao/fihobi/HOD_fit_yuan/'          # where to output galaxy mocks
    subsample_dir: '/pscratch/sd/s/siyizhao/fihobi/subsample/'                 # where to output subsample data
    z_mock: 0.8                                                              # which redshift slice
    cleaned_halos: True                                                     # load cleaned halos?

prepare_sim:
    Nparallel_load: 5                                          # number of processes. peak memory usage will increase by this factor.
    Nthread_per_load: 'auto'                                   # number of threads per process (auto uses the affinity mask)

# HOD parameters
HOD_params:
    want_ranks: False               # want to implement satellite profile flexiblities?
    want_AB: False                  # are you planning on implementing assembly bias (AB)?
    # Ndim: 1024                     # size of grid for grid based local environment, we opted to use neighbor count based local environment instead
    density_sigma: 3               # scale radius in Mpc / h for local density calculation
    tracer_flags:                  # which tracer do we want?
        LRG: True
        ELG: False
        QSO: False
    want_rsd: True                 # want RSD?
    write_to_disk: False

    # parameters for setting up the HOD of LRGs
    LRG_params:
        logM_cut: 12.78
        logM1: 13.94
        sigma: 0.17
        alpha: 1.07
        kappa: 0.55
        alpha_c: 0
        alpha_s: 1
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0
        ic: 1.0

    # parameters for setting up the HOD of ELGs
    ELG_params:
        p_max: 0.53
        Q: 10.
        logM_cut: 12.3
        kappa: 1.
        sigma: 0.58
        logM1: 13.53
        alpha: 0.9
        gamma: 4.12
        A_s: 1.
        alpha_c: 0
        alpha_s: 1
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0
        ic: 1.0

    # parameters for setting up the HOD of ELGs
    QSO_params:
        p_max: 0.33
        logM_cut: 12.21
        kappa: 1.0
        sigma: 0.56
        logM1: 13.94
        alpha: 0.4
        A_s: 1.
        alpha_c: 0
        alpha_s: 1
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0
        ic: 1.0

# clustering parameters
clustering_params:
    power_type: 'wp'
    # clustering_type: 'multipole'
    bin_params:
        logmin: -0.8253868325840207
        logmax: 1.5079465003065975
        nbins: 14
    pimax: 30
    pi_bin_size: 5

# ===========================================================================================
# The following dictionaries are for using the provided emcee/likelihood templates. They
# are not needed for using the AbacusHOD class and running HODs.

# parameters that indicate where the observed data that you would like to fit live.
data_params:
    tracer_density_mean:
        LRG: 5.0e-4 # (Mpc/h)^-3
    tracer_density_std:
        LRG: 1.0e-4 # (Mpc/h)^-3
    tracer_combos:
        LRG_LRG:
            path2power: '/global/homes/s/siyizhao/projects/fihobi/data/l/data4zenodo/LRG_main_z0608_wp.dat'
            path2cov: '/global/homes/s/siyizhao/projects/fihobi/data/l/data4zenodo/LRG_main_z0608_wpcov.dat'
#       LRG_ELG:
#            path2power: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_target_standard.npz'
#            path2cov: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_cov_mock_div8.npz'
#        ELG_ELG:
#            path2power: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_target_standard.npz'
#            path2cov: '/mnt/marvin1/syuan/scratch/targets_xi/data_xi_cov_mock_div8.npz'


# params to be fit for dynesty
# [mapping_index, mean, min, max, std, tr_type]
dynesty_fit_params:
    logM_cut: [0, 13.3, 12, 13.8, 1.0, 'LRG']
    logM1: [1, 14.0, 12.5, 15.5, 1.0, 'LRG']
    sigma: [2, 0.5, 0.0, 3.0, 0.5, 'LRG']
    alpha: [3, 1.0, 0.0, 2.0, 0.5, 'LRG']
    kappa: [4, 0.5, 0.0, 10.0, 0.5, 'LRG']
    # alpha_c: [5, 0.4, 0.4, 'LRG']
    # alpha_s: [6, 0.8, 0.4, 'LRG']

# configuration parameter for dynesty
dynesty_config_params:
    # path2output: /global/homes/s/siyizhao/data/dynesty/test
    path2output: /pscratch/sd/s/siyizhao/fihobi/HOD_fit_yuan/dynesty
    chainsPrefix: test
    rerun: 1
    nlive: 200
    rseed: 42
    bound: 'multi'
    method: 'unif'
    maxcall: 50000
